#!/bin/zsh
echo "The name of the script is \n$0"
echo "The first argument is \n$1"
echo "The name of the second argument is \n$2"
echo "The number of arguments passed is \n$#"
echo "The list of arguments passed is \n$@"
echo "Exit status of most recently run process\n$?"
echo "Pid of the current script is \n$$"
echo "User \n$USER"
echo "Hostname \n$HOSTNAME"
echo "No of seconds passed since start of script \n$SECONDS"
echo "A random number \n$RANDOM"
echo "Current Line number\n$LINENO"
